### PR TITLE
poshi-training

### PR DESCRIPTION
**Pull request by Hiba-rahimi**

### CODE REVIEW

**Comment by Hiba-rahimi** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 4 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [ecad23f941d2361f0026f2174d7d5c394f2398e9](https://github.com/liferay/liferay-portal/commit/ecad23f941d2361f0026f2174d7d5c394f2398e9)
> 
> #### Sender Branch:
> Branch Name: [poshi-training](https://github.com/Hiba-rahimi/liferay-portal/tree/poshi-training)Branch GIT ID: [803f5cec7b8afae644791a9872379b6e2a3c16d5](https://github.com/Hiba-rahimi/liferay-portal/commit/803f5cec7b8afae644791a9872379b6e2a3c16d5)
> 
> 0 out of 1jobs PASSED
> #### 1 Failed Jobs:
> * [test-portal-source-format](https://test-1-14.liferay.com/job/test-portal-source-format/6618/)
> 
> ##### For more details click [here](https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6618/jenkins-report.html).
>      [java] java.lang.Exception: Found formatting issues:
>      [java] At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.
>      [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:44)
>      [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1298)
>      [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:326)
>      [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
> [stopwatch] [run.batch.test.action: 1:28.374 sec]
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
>       [get] Getting: http://test-1-14/job/test-portal-source-format/6618//consoleText
>       [get] To: /opt/dev/projects/github/liferay-portal/20230922101343505.txt
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230922101343505.txt
>   [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
>   [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1544882271.properties
> merge-test-results:
> [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
> [beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
> [junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1224305460
> [junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
> [junitreport] Transform time: 189ms
> [junitreport] Deleting: /tmp/null1224305460
> [echo] A report with all the test results can be found at test-results/html/index.html.
> [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results

`At least one commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSITES, LCD, LHC, LOOP, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin ci.properties in the liferay-portal repository.`
What this error means?
For every pr that you send to the repository's liferay, you should to use these terms for your branch and title before, like this example "LPS-12345 - Exercice from Poshi" and the commit like that "LPS-12345 - Automation MyTestFile"
I didn't teach for you before because I would like to show on practice why the importance to source format at liferay

Can you fix it @Hiba-rahimi  and send me a push again please, thnks

**Comment by pedroamarall** [comment]
Hey @Hiba-rahimi I saw that you sent this [new pr](https://github.com/pedroamarall/liferay-portal/pull/36) with the same testcases, for this reason, I will close this pr okay. Thanks!

**Pull request closed without merging**
